# Generated by Django 4.2.11 on 2026-09-05 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parsed_skills", models.JSONField(default=list)),
                ("raw_text", models.TextField(blank=True)),
                ("experience_years", models.IntegerField(default=0)),
                ("seniority_level", models.CharField(default="entry", max_length=32)),
                ("summary", models.TextField(blank=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="resumes/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resumes",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
